DROP DATABASE IF EXISTS pulseScan;

CREATE DATABASE pulseScan;

USE pulseScan;

CREATE TABLE users (
	ID PRIMARY KEY INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
    fileName INT NOT NULL AUTO_INCREMENT
);